### ISSUE TITLE
Open questions discussion

### ISSUE THREAD

**Issue by guybedford** [jkrems/proposal-pkg-exports#1]
> Should there be a way to allow deep imports?

I tend to think yes. Some users may still need this, and the burden of manual listing isn't negligible.

> Possible solutions include:

> It's always allowed and tried if an explicit mapping isn't found.

This makes the entire feature opt-in as opposed to opt-out. I'm tempted to say that if we could ship this it should be opt-out over opt-in for the ecosystem benefit?

> It's configured via a special key in the import map (e.g. "/": "./lib/").

This is a nice idea actually. Although it still requires extensions to be explicit - would we want that? Or do we want to make extensions easy to exclude? We could possibly even do automatic extension checking just for these entry points only?

> It's configured via a dedicated flag ("esm-allow-deep-import": true).

Perhaps this could be an `esm-import-map: true`? (doesn''t make sense with this name, but replace that with "entries" or something and it works)

> Should explict /default be allowed?

I don't think this is a worrying collision since it doesn't restrict a default.js file, just a default named entry point which seems fine to reserve.

> // Does this work and do the same thing?
> import x from 'some-pkg/default';

Happy either way on this. Perhaps its nice to have the default only mean the main to avoid any odd hacks...?

**Comment by hybrist** [comment]
> Happy either way on this. Perhaps its nice to have the default only mean the main to avoid any odd hacks...?

If we go for maximum equivalence with `import def from 'x'`, then `import { default as def } from 'x'` should work. Which in this case would be `import 'x/default'`. That said: I'm currently leaning towards not allowing it. It feels awkward to have one more verbose way of saying the same thing. And I don't see any realistic advantage of allowing `import 'x/default';`.

> This makes the entire feature opt-in as opposed to opt-out. I'm tempted to say that if we could ship this it should be opt-out over opt-in for the ecosystem benefit?

I think there is value to make it opt-in. That way packages that do want to expose every possible file that ships have to actually say so. And given our brainstorming in the meeting, it seemed like a fairly fringe benefit to have a package that really wants true `x/` behavior by default - which would include that deep imports need file extensions etc..

> This is a nice idea actually. Although it still requires extensions to be explicit.

Yes, that is by design I think. It feels weird to have a magic file extension but only for deep imports using bare specifiers..?

**Comment by GeoffreyBooth** [comment]
A few thoughts:

- I think we should keep automatic extension resolution off the table for now. It adds a lot of questions about how to handle `.js`, and also WASM etc. If we don’t need it to solve this, I think we should leave it out of the scope we’re working on for this current Phase 2 effort. Much easier to add later than remove later.

- I think that exposing a package’s entire file tree should be opt-in rather than opt-out. Regular `export` statements force users to be explicit about what they’re exporting, and I feel like what we’re designing in `package.json` should echo `export` statements. It also just feels like a better software design principle to enforce the concept of a package author creating a public API. If the user really wants to expose every single file, they can explicitly list them all (or use a tool to do so).

**Comment by hybrist** [comment]
Geoffrey and I just created an updated draft. Most excitingly it gets rid of default and unifies behavior a little better: https://github.com/jkrems/pkg-import-map#example

**Comment by guybedford** [comment]
Nice work refining it. I really like bringing in the trailing slash concept, as it solves a common problem with `require('x/dist/y')` being mappable!

Agreed lets keep file extensions off the table then for now.

> I think that exposing a package’s entire file tree should be opt-in rather than opt-out

Yes I think this is a major benefit of the proposal. And it is a much nicer opt-in now with one line to add the base map anyway.

**Comment by hybrist** [comment]
I think this issue should be covered for now. I'll open dedicated issues for the items we just discussed in the meeting.
