### ISSUE TITLE
Why implemented only for bare specifiers?

### ISSUE THREAD

**Issue by Fishrock123** [jkrems/proposal-pkg-exports#12]
> The `package.json` `"exports"` interface will only be respected for bare specifiers, e.g. `import _ from 'lodash'` where the specifier `'lodash'` doesn’t start with a `.` or `/`.

I assume this is for web-compat? Could a note be added?

**Comment by hybrist** [comment]
It's more to prevent confusion since they apply to *consumers* of the package. Overriding random other specifiers or paths outside of the current package seems like it would be hard to debug.

For overriding specifiers inside of the package boundary, the proposal now has the `imports` field which mirrors the name (and semantics) of the `imports` field in import maps.
