### ISSUE TITLE
What are the tradeoffs in choosing this over the existing solution?

### ISSUE THREAD

**Issue by zenparsing** [jkrems/proposal-pkg-exports#24]
Certainly if we were designing Node from scratch, we would likely choose this explicit export maps proposal over the current lookup algorithm. It's very clean and nice. Well done!

However, we are not starting from scratch and if we go with this proposal we will have two ways of supporting supporting "deep package imports":

- The current solution, where the package directory is searched
- The proposed solution, where package.json is consulted

Both will work for ESM, but because of backward compatibilty constraints they won't both work with CJS. What can we say about the tradeoffs of inventing something new for ESM?

I'll add my thoughts to start the conversation.

I'm concerned that this will make the transition phase more difficult than it otherwise needs to be. For instance, let's say that I'm publishing a package where I want to support older versions of NodeJS. In that case I need to publish CJS as well as ESM. If I want to also add "deep imports" to this package I'll need to add both an "exports" map in CommonJS (to handle the ESM case) and also individual modules in the root of the package (for the CJS case). This seems more of a pain than the current solution of including both ".js" and ".mjs" files at the package root.

On the other hand, going with this proposal will result in a cleaner solution in the far future.

On the *other* hand, although I occassionally use deep imports, my usage is rare enough that I don't really care too much about making things super clean.

Any other ideas?

**Comment by GeoffreyBooth** [comment]
Even in the proposed solution, we still have the file path searched if the map is something like `"./": "./"`—that maps the root to the root, a.k.a. the current CommonJS behavior. So if anyone wants that behavior in ESM, they can have it (though they need to specify that they want it in `package.json`).

I’m thinking that often users might _want_ separate paths resolved for CommonJS versus ESM. If you look at many of the packages we investigated, you find CommonJS entry points like `./dist/index.js` and ESM entry points like `./src/index.js`, where some build tool like Babel is transpiling ESM `./src` into CommonJS `./dist`. In order to maintain equivalence between the module systems, where the readme can say something like “for CommonJS, use `const S3 = require('aws-sdk/s3')` or for ESM, use `import S3 from 'aws-sdk/s3'`,” then you’ll need a different mapping for ESM than you had for CommonJS. People are already writing the latter code now, since Babel transpiles it all down to CommonJS and it “just works” because it matches, but that convenience will break if we don’t provide a way to map paths separately per mode (or at least for ESM, and CommonJS defaults to the file system paths). So this isn’t just a good idea that maybe Node should’ve added long ago, it’s also a way to _improve_ the transition process since it’ll save end users from having to rewrite as much code.

Also not relying on file extensions allows the use of ESM in `.js` files, which is another goal: https://github.com/GeoffreyBooth/node-import-file-specifier-resolution-proposal/

**Comment by zenparsing** [comment]
> Even in the proposed solution, we still have the file path searched if the map is something like "./"

Ah, good point.

> Also not relying on file extensions allows the use of ESM in .js files

Yes, I agree that's an important goal.

But I believe that using file extensions for ESM/CJS "deep imports" is compatible with that goal if we (a) search extensions and (b) prefer ".mjs" when importing. No?

**Comment by GeoffreyBooth** [comment]
> But I believe that using file extensions for ESM/CJS “deep imports” is compatible with that goal if we (a) search extensions and (b) prefer “.mjs” when importing. No?

I’m not sure how you can publish a dual-mode (ESM and CJS) package that both uses `.js` for ESM and also relies on file extension to tell the difference between ESM and CJS files.

Also, searching extensions is itself something that a lot of people want Node to stop doing. It’s a big performance hit when resolving `require('./foo')` to have to search `./foo.mjs`, `./foo.js`, `./foo/index.mjs`, `./foo/index.js`, possibly `./foo.ts` and so on. Part of the appeal of the package exports proposal is not just to make explicit what is intended to be the public API, but also to put an end to this hunt-and-peck searching for a file that matches the specifier.

**Comment by hybrist** [comment]
One aspect that's missing from the discussion so far: Browser equivalence. It is *possible* to generate something like an import map for the CommonJS-like resolution. But it requires quite a bit of work and is super verbose. E.g. you'd have to backtrack every single file to each specifier that might be used to import it. The semantics of this proposal are designed to allow us to generate a full\* import map from the package meta data using a very simple algorithm ("concat key, concat value, add to map").

In addition, in its simplest form `"exports": "./some/file.mjs"` or `"exports": "./some/file.wasm"` is just a way to provide a non-CommonJS entrypoint. The ability to expose additional files is just icing on top.

**Comment by guybedford** [comment]
I don't think the dual mode experience is made harder than it should be here. Rather I think the general subpath experience is what is made harder. Consider:

```
- main.js
- main.mjs
- sub.js
- sub.mjs
```

Now if I was previously just supporting ES modules without any CJS fallback support I'd already have needed to add exports to my package:

```json
{
  ".": "./main.mjs",
  "./sub": "./sub.mjs"
}
```

that is, the cost here of adding "exports" is not a dual mode cost, it is a permanent cost of subpaths with this proposal.

The only work required to support the dual mode is really just making the CJS versions available and adding the CJS main, which is needed however this is spun.

So I'd suggest that if we're talking about an "exports" cost, then we should consider that cost as a completely separate thing to the dual mode use case.

In terms of automatic extensions, I don't see that as having any benefit over being explicit about extensions in the dual mode case - that seems to be more of an aesthetic argument to favour "pkg/x" over "pkg/x.js" in CJS and "pkg/x.mjs" in ESM which I personally prefer as an explicit pattern when using `exports: { "./": "./" }`.

**Comment by hybrist** [comment]
Trying to close out existing discussion threads to make sure we're not missing important questions: I'm going to close this issue but please reopen if there's something in here we still need to work through!
