### ISSUE TITLE
Subpath folder mappings deprecated according to Node.js documentation

### ISSUE THREAD

**Issue by dmail** [jkrems/proposal-pkg-exports#49]
This repository documents `exports` field with an example at https://github.com/jkrems/proposal-pkg-exports#1-exports-field.
In this example one of the configuration correspond to something called `Subpath folder mappings` in Node.js documentation. This configuration is deprecated according to [Node.js documentation 15.x](https://nodejs.org/dist/latest-v15.x/docs/api/packages.html#packages_subpath_folder_mappings)

![image](https://user-images.githubusercontent.com/443639/109670032-03320f80-7b73-11eb-88d5-08dad07e8a85.png)

Node.js documentation and this repository documentation are not in sync, can you explain me why?

**Comment by hybrist** [comment]
> Node.js documentation and this repository documentation are not in sync, can you explain me why?

I can attempt to explain the reverse. After active work on defining exports wound down and a lot of work was put into creating proper documentation in the node docs, this repo should've quickly become completely outdated. But @guybedford put in a lot of unpaid work to port updates to this repo as well as improving the content in the nodejs docs. That's why some things around imports are in here that were introduced after the primary work moved to node core.

Depending on how future work with bundlers goes, it may be less confusing the update the README on this repo to point to the node docs and archive the proposal repo.

**Comment by dmail** [comment]
To give you some context by the way: 
I was asking this question because I made a tool to generate import maps from `package.json`. This tool takes into account every `exports` field eventually found in `package.json`. The recent depreciation of "subpath folder mapping" make `exports` no longer fully convertible to import maps. I wanted to know a bit more about the situation. In the end I have added  a warning about that topic in my documentation (https://github.com/jsenv/jsenv-node-module-import-map#subpath-import-warning).

Thank you for taking the time to respond to my question.  Can't wait to see import resolution getting stable, thank you for your work here. 

Have a great day! :)

**Comment by guybedford** [comment]
@dmail some ways to get around this include:

* Handle the `/*: /*` to `/: /` conversion as you are doing
* For other `/*.js` style cases, enumerating the list from the package is an option
* When all the mappings in a folder are explicit mappings (`./y.js: ./x/y.js` and `./z.js: ./x/z.js`( then setting `pkg/: pkg/x/` can be a sort of "deduping".

Wildcard exports always had this risk, but the arguments for them in Node.js were compelling enough to take it. It's likely we won't see them in import maps proper. But I'm hopeful that techniques like the above can bridge the gap here.

**Comment by dmail** [comment]
> For other /*.js style cases, enumerating the list from the package is an option

I can think about two options when the script finds `"./feature/*": "./features/*.js"` in the `package.json` `exports` field: 

a) Use filesystem
Downside of relying on filesystem:  will certainly generate a bunch of remapping never actually imported in the codebase.

b) Parse the code to find static and dynamic imports
Downside of parsing files: makes the tools more complex because it suddenly needs a js parser that is configurable to support TypeScript, jsx, ...

> When all the mappings in a folder are explicit mappings (./y.js: ./x/y.js and ./z.js: ./x/z.js( then setting pkg/: pkg/x/ can be a sort of "deduping".

I don't understand 😅 . Do you mean that if all mappings are explicitely written in the package.json, they can be copied as such in the import maps?

> Wildcard exports always had this risk, but the arguments for them in Node.js were compelling enough to take it. It's likely we won't see them in import maps proper. But I'm hopeful that techniques like the above can bridge the gap here.

I think omitting extension creates confusion and complexity in tooling. It is still not crystal clear why Node.js (and TypeScript) encourages directly or indirectly to omit extension.

![image](https://user-images.githubusercontent.com/443639/109824019-bca6e880-7c38-11eb-8feb-ee3cc56bb413.png)

**Comment by guybedford** [comment]
@dmail it makes the .mjs / .ts / .js extension an implementation detail. Also many package authors are accustomed to publishing `pkg/feature` instead of `pkg/feature.js`. Import maps allow us to omit extensions, `./: ./` effectively gives preferential treatment to extensions. There were cases of authors publishing huge "exports" fields with separate entries because `./x/: ./y/` wasn't sufficient. Even to the point of npm having trouble with the size of the manifests. Wildcards also ensure not exposing unnecessary files by acting as a filter which is a powerful property. We let users make the decisions by giving them the flexibility. We had import maps in mind, but this wasn't seen as a blocker or a strong enough problem - enumerating from the file system as a package processing step isn't so bad honest.

Import maps always have the problem of unnecessary bloat regardless though. In general basing them on a tracing analysis operation is always a needed optimization, even more especially since they are first load blocking it justifies that work.

I mean that the import map:

```json
{
  "imports": {
    "pkg/y.js": "/pkg/x/y.js",
    "pkg/z.js": "/pkg/x/z.js"
  }
}
```

can be automatically simplified to:

```json
{
  "imports": {
    "pkg/": "/pkg/x/"
  }
}
```

as an optimization. I also prefer extensions for this reason, but we cannot dictate (or if you want to, advocate!).

**Comment by dmail** [comment]
Got your point about .mjs / .ts / .js becoming implementation detail.
Also got it for the deduping of mappings declared in the importmap.

I will not advocate for extensions but would give all my support and adoration to someone that would :D

Thanks for the valuable info @guybedford and @jkrems
