### ISSUE TITLE
Consider supporting patterns

### ISSUE THREAD

**Issue by weswigham** [jkrems/proposal-pkg-exports#8]
Eg,
```json5
{
    "*": "src/*.js"
}
```
it's a convenient shorthand for when you want to export all of your internal bits.

**Comment by hybrist** [comment]
Is this something people actually do? Ignoring lodash for a second (which surely could just write a quick script) - are there real packages that would use this pattern? This feels like it's making it easier to expose file system layout as something that *looks* like a stable layout. It also means that we'd need to introduce more complex precedence rules.

In short: It feels like an anti-feature to me unless I'm missing some important use case.

**Comment by weswigham** [comment]
We have a [`paths`](https://www.typescriptlang.org/docs/handbook/module-resolution.html#path-mapping) feature in TS which is effectively this (also [`typesVersions`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-1.html#version-selection-with-typesversions) which uses similar patterns and resides in a `package.json`!) - people use patterns like this all the time. As much as "it feels like an antipattern" people actually _do_ often want to expose large sets of folders and files.

**Comment by hybrist** [comment]
Let me clarify: The proposal already does support exposing whole directories. For example the following will allow importing all files in the package:

```
{
  "/": "./"
}
```

What I'm objecting to is having the ability to make these look like true, well-defined entry points.

> As much as "it feels like an antipattern" people actually do often want to expose large sets of folders and files.

The issue is this proposal aims to make it immediately visible when you are importing a file and when you are importing a reference / public API. If somebody wants to expose a directory structure, they can. But it would be exposed as a directory structure.

**Comment by weswigham** [comment]
I'm not sure I catch the distinction? The premise is simply that you take a package local specifier that matches a pattern on the left, then map it to the path on the right, no?

**Comment by hybrist** [comment]
The premise is that you map a fixed pattern on the left to a URL on the right. Once we start introducing patterns on the left, decisions become murky. Does `*` match a path segment or any number of characters? Does it transfer encoding? Can we still look at a single location or how do we sort what we try and in what order?

And all that just so that *some* package owners (which we haven't actually clearly identified yet, thus my assumption that we are talking about an edge case) can bulk expose an arbitrary and unchecked number of files without their consumers adding an explicit extension. And it doesn't handle cases where some of those files might be of different types (`.json` / binary AST / WASM).

Again: Maybe I'm missing something fundamental about the feature request but it doesn't seem to add any fundamental capability, makes the implementation and usage harder, and is - afaict - incompatible with import maps, requiring us to fork semantics.

Can you give a concrete example of using this feature or of an existing project that would need it?

**Comment by weswigham** [comment]
> Again: Maybe I'm missing something fundamental about the feature request but it doesn't seem to add any fundamental capability, makes the implementation and usage harder, and is - afaict - incompatible with import maps, requiring us to fork semantics.

I'm not really sure how it would ever make usage _harder_, since you'll only ever be impacted by a pattern if you want to write a pattern. It does offer some interesting new abilities though, like mapping   sets of files at once without external tooling.

I very much get where you're coming from, we literally just had the same debate within the TS team about `typesVersions` - I myself was advocating that since most of our expected usage of it is DT, we should just do static maps (like this); however we discussed it a bunch and looked over how it would be used, in practice, and found that for the average user, a single entry with a `*` for mapping all the paths into the right place. I think the "mindful developer" who puposely exposes individual files as "public" would be quite a paradigm shift from where we are today.

**Comment by hybrist** [comment]
> I think the "mindful developer" who puposely exposes individual files as "public" would be quite a paradigm shift from where we are today.

I'm not sure I understand where that is coming from. All guidance I'm seeing in the ecosystem is saying "if you reach into `lib` or `src`, you're doing it wrong". IIRC babel went as far as adding protective code to all their modules to *prevent* people from reaching in because consumers of babel were messing with babel's ability to refactor.

I would put DT in the same camp as lodash - these are super specialized edge cases that come with all sorts of automation built around it already. This doesn't seem to be a common case for everyday module authors..?

**Comment by weswigham** [comment]
Sufficiently large projects have private internals and files whose APIs are entirely internal, yes, but the majority of packages are smaller where every published file (or most files) in the package can safely be considered part of the API (`left-pad` is pretty representative). Lodash is a large library that happens to work like this, but there are a huge number of small libraries on npm that do as well. And it's not like having patterns available prevents anyone from only exposing what they want to! It's just a shorthand for exposing multiple things on one line! This isn't even an argument about a default or anything! Just a suggestion that if I _do_ happen to have a suite of things I want exposed, I should be able to expose them easily.

And patterns do have utility! Many packages that do have an internal/external split that I've seen have, eg, an `internal` folder or an `api` folder to indicate which half is which; there's a lot of utility in being able to write a pattern that matches all of the things that could be in one of those folders when you first make it, so what you expose in the future can then be left up to convention (where it is on disk) rather than requiring tedious configuration updates later on.

**Comment by hybrist** [comment]
> And patterns do have utility! Many packages that do have an internal/external split that I've seen have, eg, an internal folder or an api folder to indicate which half is which;

Okay, but that's already handled. See above - this is part of the proposal so I'm not sure how it is relevant for this discussion..?

> Sufficiently large projects have private internals and files whose APIs are entirely internal, yes, but the majority of packages are smaller where every published file (or most files) in the package can safely be considered part of the API (left-pad is pretty representative).

`left-pad` is an example where - afaik - there's zero value in exposing directory structure. If `import leftPad from 'left-pad'` works, why would anybody need `import leftPad from 'left-pad/lib/impl.js'`? I'm not aware of libraries that are small enough to not have any supporting files at all while big enough that declaring an API is cumbersome (if they even expose more than one file). That's why I'm asking for examples that would fit that bill.

**Comment by weswigham** [comment]
Like, huge projects like `babel` and `react` are moreso the exception than the rule. I've reviewed countless single-function and handful-of-files declarations for npm packages on DT (anecdotal, I know). I'm just saying it pays to be flexible here  - you don't really lose anything by allowing people to be more expressive with the field, and glob matching is pretty common. (Tbqh it's rare to see a config file that explicitly lists every file). You'd quickly find that those questions you have have pretty reasonable default answers were you just pick up an off-the-shelf just globbing package.

Anyways, if you want an example (not mine), I was looking at `amcharts` related code for a bug last week, and the submitted repro had [a pretty big API](https://github.com/Pauan/amcharts4-typescript-example-fast/tree/master/src). Just mapping some `api` folder won't work here, since you need to also prevent direct access to the `.internal` folder.

And that's before you get into esoteric schemes where, eg, each file has an adjacent `.priv.js` that shouldn't be exposed or something.

I just think full pattern support would be more flexible. I really doubt supporting patterns would actively hurt much of anything.

**Comment by hybrist** [comment]
> You'd quickly find that those questions you have have pretty reasonable default answers were you just pick up an off-the-shelf just globbing package.

The implementation concerns are more about what comes after globbing (or might not be covered by *nix globs). And I'm aware of complexities there once placeholders come into play from writing asset pipeline code. Glob expansion is easy but that's not what I'm talking about when it comes to "route matching" (which this effectively is if you squint your eye).

> (Tbqh it's rare to see a config file that explicitly lists every file).

The proposal doesn't suggest that. The proposal suggests either listing files or whole directories.

> I've reviewed countless single-function

How would a single-function package use the glob support you describe above? If it wouldn't, why is it relevant in this context? You brought up this example repeatedly but never explained how globs would be useful there. For me the number of single-function (or single exported file) packages is a reason *against* the need for globs..?

> handful-of-files declarations for npm packages on DT

Would it be all that bad to list a handful of public entries? I assume you'd want to document them anyhow? I certainly have packages that export a handful of files that would become *simpler* if I could declare them in `package.json` instead of having to create dummy files in the package root directory.

> And that's before you get into esoteric schemes where, eg, each file has an adjacent .priv.js that shouldn't be exposed or something.

This kind of sentence is why I asked for being explicit. How would you express that kind of thing in a glob? Are we now talking about arbitrary RegExp so that it can exclude certain matches..?

> Just mapping some api folder won't work here, since you need to also prevent direct access to the .internal folder.

So... how would that look in your glob solution? Is this a case where it happens to work because * won't match dot files by default? But if a package would use an `internal` folder, that wouldn't be supported? So somebody doing the innocent refactoring to make `internal` a non-hidden folder would be in for a rude awakening?

I feel like if you actually tried expressing these kinds of cases as globs (the explicit examples I asked multiple times for now), you would see where my "harder to use for consumers" is coming from. Especially if the next person needs to come in and understand what's going on.

**Comment by hybrist** [comment]
P.S.: I also looked at amdcharts4. I don't see the harm in either mapping `{ "/": "./dist/es2015" }` or mapping the following to exclude internal:

```js
{
  "/core": "./dist/es2015/core.js",
  "/charts": "./dist/es2015/charts.js",
  "/maps": "./dist/es2015/maps.js",
  "/lang/": "./dist/es2015/lang/",
  "/themes/": "./dist/es2015/themes/",
}
```

This way the examples directory is also excluded from direct import, preventing people from depending on implementation details there. And it also works if `themes` would contain JSON files etc..

**Comment by GeoffreyBooth** [comment]
A few thoughts on this:

1. We can always add support for globs/patterns later. Nothing in the current proposal prevents that addition.
2. The browsers’ import maps proposal doesn’t support globs and almost certainly never will, because globs can’t be resolved without file system searching, and that’s not something that browsers can reasonably do. They don’t support automatic file extension resolution for that reason, requiring users to type `.js` or `.mjs` explicitly, because they don’t want the browser to make repeated network lookups as it hunts for a match. (This is [discussed](https://github.com/domenic/import-maps#packages-via-trailing-slashes) in that proposal.) One of our overriding goals is browser equivalence, of course, and so I think we should try to conform to browsers here.
3. It would be trivial for a tool to be written to enable globbing support. Say I wrote a tool called `exports-glob-expander`. It would be a CLI tool that would look for a `package.json` in the current folder, and look for a `exports-globbed` key. That key would be an object just like this repo’s proposal, but the keys and/or values would include globs. My tool would scan the folder tree of the current package and resolve all the globs, and update the `package.json` `exports` key as needed to match what it found. So in other words, users could get globbing support via a userland build tool.

So I think it’s worth leaving out, at least in the first iteration. If there’s great demand for it, so much so that a CLI tool is deemed insufficient, we can consider implementing it in a safe way.

**Comment by weswigham** [comment]
@GeoffreyBooth

On your second point: browser equivalence is pointless for a feature like this. A browser's not going to read a `package.json` file for metadata, so you're going to need a tool to generate a name map from this (plus any other resolver behaviors) _anyway_ (and I'm fairly certain that's always going to be the case unless by some happenstance a normal `package.json` becomes parseable as a name map - along with the nested packages jsons for your dependencies... Seems unlikely). Aiming for browser equivalence involving the name maps proposal is seems like a red herring - the name maps proposal exists to make porting projects using nodelike paths to browser resolution easier, not to make node resolution more like the browser. I don't think there's many scenarios where I'd ever want to generate a map by hand, if I'm honest - I'd almost always have something else as the ultimate source of truth for how my things resolve.

On your third point: It would be "trivial" to write a tool to hook resolution or the node environment to make this proposal unnecessary (I mean @std/esm already exists for one) that doesn't mean it's not, though - the entire point of this proposal is builtin convenience. Nobody _needs_ to use bare imports, technically, we just really _want_ to because we're familiar with it from cjs. The feature is entirely in the service of usability and familiarity - maximizing that usability (and ideally familiarity) seems logical.

I like to think of it this way: If you implemented this proposal as a loader, and I implemented this proposal as a loader but also supported globbing, All else the same, I'd wadger that mine would see more use. It provides value to those who want it and doesn't detract from what others would use it for. That's why I think it has value.

**Comment by GeoffreyBooth** [comment]
@weswigham If you want to propose supporting globs, I think you need to write out a detailed proposal explaining how they’d work. The current proposal treats the left-hand side as string concatenation on the package name, and that was intentional. We chose string concatenation to avoid the complexity of paths when paths aren’t really the appropriate paradigm, as import specifiers are essentially relative URLs (and are treated as such in the import maps proposal). If we allow globs on the left side, how would they work? How would that translate to another glob on the right-hand side? How would you resolve conflicts when there are multiple matches either of separate left-hand-side keys or of files matched by the right-hand-side glob?

There’s a lot of complexity to work out with supporting globs, which is why I’m inclined to leave it as a “maybe support later” improvement. If you can work out the details and all the edge cases and it all checks out, then sure, it’s worth considering.

Browser equivalence isn’t pointless for this feature. Import maps are intended to be generated from `package.json` files. That’s only possible if the data in `package.json` can be translated into the form that import maps expect. Also if import maps treat the left-hand side as URLs, and this feature is obviously so similar to it, it’s a usability concern if our version doesn’t also treat the left-hand side also like URLs.

**Comment by weswigham** [comment]
> Browser equivalence isn’t pointless for this feature. Import maps are intended to be generated from package.json files. That’s only possible if the data in package.json can be translated into the form that import maps expect. Also if import maps treat the left-hand side as URLs, and this feature is obviously so similar to it, it’s a usability concern if our version doesn’t also treat the left-hand side also like URLs.

Any static resolution scheme (including cjs as it exists today) can be mapped into package maps (partially thanks to the scoped resolution bit added to the proposal) - you just have to run the resolution and then record the final path for each possible (source, specifier) pair. Full static FS overlays like yarn's PNP file and npm's tink package map both go even father and just serialize almost the entire directory structure into a document to avoid disk hits and work very similarly in that regard. I'm pretty certain you could generate a perfectly accurate import map from one of those.

Actually looking at where the import map proposal is today, I'm certain that what node does for it's resolution in esm absolutely does not matter at all - any reasonable static resolution scheme chosen can be serialized into the map (which was a goal of the import map proposal!). Contorting node's resolution to have map-fragments built into it just to be more like the proposal seems unnecessary (and is, if I'm honest, depearting from the node ecosystem a bit). Tbqh, the remaining utility here is just having specified pkg entry points rather than implied ones; and if you want that you can probably just write a version that applies to all node resolution equally - cjs and future esm (which'd probably be neat - you can probably prototype it for cjs pretty easily with a `require` wrapper). And it's not really an `esm` concern at that point, more a `node` as a whole one (probably a good one at that).

You can ignore this suggestion; talking (writing?) through it has convinced me the concept as a whole doesn't have too much use in `node` - `node` can use normal `cjs`- like resolution for `esm` and it's easily adaptable to import maps in it's current form via tool; so what's the point in dumping years of community and tooling behind the current resolver?

**Comment by hybrist** [comment]
> any reasonable static resolution scheme chosen can be serialized into the map

I think we ignore what qualifies as reasonable then. :) To serialize a package using CJS rules into an offline in-memory lookup table (for efficient resolution without resource access), you need to:

1. List all files in the package, including resolving all symlinks (throwing if the links go outside of the package boundary because you enter 🤷‍♂️ land).
1. For each file, backtrace what the possible inputs are.
1. Deduplicate ambiguous cases based on preference (e.g. `.js` beats `.json`).

It's possible - true. But you now have a bare specifier system that's completely out of sync with how non-bare specifiers work because for URL-based imports none of those rules would apply.

> Full static FS overlays like yarn's PNP file and npm's tink package map both go even father and just serialize almost the entire directory structure into a document to avoid disk hits and work very similarly in that regard.

This proposal is aimed at making writing these "overlays" a lot simpler. Because you don't need any additional data beyond the packages & their `exports` (e.g. flattened into an import map) to do all resolution. The import map idea does not only apply to browsers - it's specifically interesting in node to allow:

1. Dynamic resource layouts that don't require multiple copies of each package in a specific directory structure, on disk, inside of the project.
2. Zero-stat import resolution. A packager can generate an import map by just processing package meta data and knowing where the packages are stored. From then on, the absolute URL of every import can easily be calculated in memory w/o hitting the disk.

All this is *technically* possible with the legacy CJS semantics. It's just much harder and leads to lots of inconsistencies. I'd rather not turn ESM into a C++ layered on top of CJS's C semantics.

**Comment by hybrist** [comment]
> All this is technically possible with the legacy CJS semantics.

I take that back. Pretty much any implementation of this I'm aware of (tink, pnp, various in-house solutions) completely overwrites the CJS module system and reimplements it. Because it's *not* practical on top of it, at most you can simulate (parts of) the CJS module system.

**Comment by weswigham** [comment]
> All this is technically possible with the legacy CJS semantics. It's just much harder and leads to lots of inconsistencies. I'd rather not turn ESM into a C++ layered on top of CJS's C semantics.

My argument here is simply that any nontrivial project for the foreseeable future will have cjs in the dependency tree and to produce one of those overlays you'll be simulating cjs anyway. It is unavoidable. So making it easier to generate one seems like a moot point in that regard. And since I do see cjs style resolution as beneficial and convenient, I don't see why its' support wouldn't be carried forward.

**Comment by GeoffreyBooth** [comment]
> since I do see cjs style resolution as beneficial and convenient, I don’t see why its’ support wouldn’t be carried forward.

I don’t understand this complaint. @weswigham if you do this:

```js
{
  "name": "request",
  "version": "0.0.0",
  "exports": {
    "": "./index.mjs",
    "/": "./"
  }
}
```

Then you’re replicating CommonJS’ behavior of exposing an entire package’s contents. That’s what the trailing slashes do, the same as in the import maps proposal. Globs aren’t needed.

So this proposal starts with what’s possible in CommonJS in terms of entry point and deep imports, and adds the ability for a package author to define a public API to restrict deep imports if they so choose. I don’t see why people would prefer CommonJS over this, other than for automatic file extensions and folder indexes. Globs would add a more convenient way to filter what files or folders to expose, at the expense of potentially significant added complexity, but there’s no functionality like that in CommonJS.
